name: partner
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  date_picker_timeline: ^1.2.5
  intl: ^0.19.0
  get: ^4.7.2
  device_preview: ^1.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  location: ^7.0.1
  url_launcher: ^6.3.1
  geocoding: ^3.0.0
  image_picker: ^1.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/icons/info_icon.png
    - assets/icons/car_icon.png


